var areas = [
    { "ARE_Id": "1", "ARE_Descricao": "..", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "3", "ARE_Descricao": "...", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "4", "ARE_Descricao": "Todas as \u00c3\u00a1reas ", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "5", "ARE_Descricao": "Diretoria", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "6", "ARE_Descricao": "Setor de Psicotr\u00c3\u00b3picos", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "7", "ARE_Descricao": "Setor de Estoque SAIDA", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "8", "ARE_Descricao": "Setor de Estoque ENTRADA", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "9", "ARE_Descricao": "Setor de Faturamento", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "10", "ARE_Descricao": "Setor de Compras", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "11", "ARE_Descricao": "Setor de Financeiro", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "12", "ARE_Descricao": "Setor de Licita\u00c3\u00a7\u00c3\u00a3o Presencial", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "13", "ARE_Descricao": "Setor de Licita\u00c3\u00a7\u00c3\u00a3o Eletr\u00c3\u00b4nica", "ARE_Status": "1", "USR_Id": "13" },
    { "ARE_Id": "14", "ARE_Descricao": "Setor de Televendas", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "15", "ARE_Descricao": "Setor de Departamento Pessoal", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "16", "ARE_Descricao": "Setor de Apoio de Licita\u00c3\u00a7\u00c3\u00a3o", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "17", "ARE_Descricao": "Setor de Seguran\u00c3\u00a7a", "ARE_Status": "1", "USR_Id": "11" },
    { "ARE_Id": "18", "ARE_Descricao": "Setor TI", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "19", "ARE_Descricao": "Setor de cadastro", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "20", "ARE_Descricao": "Setor de Vendas Geral", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "21", "ARE_Descricao": "Setor de Estoque CONFERIDOR", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "22", "ARE_Descricao": "Setor de cobran\u00c3\u00a7a", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "23", "ARE_Descricao": "PAULO", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "24", "ARE_Descricao": "RONILDO", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "25", "ARE_Descricao": "ALBERSON COSTA ", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "26", "ARE_Descricao": "ALINE CRISTINA DE ARAUJO OLIVEIRA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "27", "ARE_Descricao": "ANTONIO NETO SOUSA LOPES ", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "28", "ARE_Descricao": "Cl\u00c3\u00a1udio Santana dos Santos", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "29", "ARE_Descricao": "Danielle de Brito Sales", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "30", "ARE_Descricao": "EDSON CAMPOS", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "31", "ARE_Descricao": "ELIEZER WALKER DA SILVA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "32", "ARE_Descricao": "ELIZANIA PEREIRA DA SILVA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "33", "ARE_Descricao": "FARMACEUTICA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "34", "ARE_Descricao": "FRANCISCO ASSIS", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "35", "ARE_Descricao": "Franscisco Souza", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "36", "ARE_Descricao": "GILMAR DE AQUINO SANTOS", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "37", "ARE_Descricao": "HANDREY RIBEIRO DA SILVA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "38", "ARE_Descricao": "Idalina Calazans dos Santos", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "39", "ARE_Descricao": "IRON PEREIRA MARQUES", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "40", "ARE_Descricao": "Jairo Willian Santos Ferreira", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "41", "ARE_Descricao": "JALES BENTO PINHEIRO", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "42", "ARE_Descricao": "Janaina Ribeiro", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "43", "ARE_Descricao": "Khezia Karolinne da Silva", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "44", "ARE_Descricao": "LEOVICTOR VIEIRA DE MELO TAVARES", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "45", "ARE_Descricao": "MARIA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "46", "ARE_Descricao": "Mayara Salom\u00c3\u00a3o Nunes Costa", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "47", "ARE_Descricao": "Paula Guimar\u00c3\u00a3es", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "48", "ARE_Descricao": "Vanuza Luiza da Silva", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "49", "ARE_Descricao": "LUCINEIDE  ", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "50", "ARE_Descricao": "ELDER OLIVEIRA SOUZA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "51", "ARE_Descricao": "JOHN PAIVA", "ARE_Status": "0", "USR_Id": "30" },
    { "ARE_Id": "52", "ARE_Descricao": "DIRETORIA", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "53", "ARE_Descricao": "Setor de Area de consultoria", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "54", "ARE_Descricao": "MERCANTIL BARRETO", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "55", "ARE_Descricao": "Setor de Contabilidade", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "56", "ARE_Descricao": "Setor Juridico", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "57", "ARE_Descricao": "Ouvidoria MB", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "58", "ARE_Descricao": "Ouvidoria Pr\u00c3\u00b3 Sa\u00c3\u00bade", "ARE_Status": "1", "USR_Id": "30" },
    { "ARE_Id": "59", "ARE_Descricao": "Teste", "ARE_Status": "1", "USR_Id": "1" },
    { "ARE_Id": "60", "ARE_Descricao": "CADASTRO DE CLIENTES", "ARE_Status": "1", "USR_Id": "13" }
]

export default areas;