var problems = [
    { "APR_Id": "1", "APR_Descricao": "Documenta\u00c3\u00a7\u00c3\u00a3o Pendente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "6", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "3", "APR_Descricao": "Pend\u00c3\u00aancia de Empenhos", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "13", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "4", "APR_Descricao": "Agendamento", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "13", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "5", "APR_Descricao": "Atraso na Entrega de Pedido", "APR_Prazo": "24", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "6", "APR_Descricao": "Diverg\u00c3\u00aancia de Pedido", "APR_Prazo": "24", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "7", "APR_Descricao": "Devolu\u00c3\u00a7\u00c3\u00a3o de Pedido", "APR_Prazo": "24", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "8", "APR_Descricao": "Entrega Parcial de Pedidos", "APR_Prazo": "24", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "9", "APR_Descricao": "Cadastro de Fornecedor", "APR_Prazo": "24", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "10", "APR_Descricao": "teste teste", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "4", "APR_Status": "0", "USR_Id": "1" },
    { "APR_Id": "11", "APR_Descricao": "Assuntos Diversos", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "5", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "12", "APR_Descricao": "Valida\u00c3\u00a7\u00c3\u00a3o de Lotes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "6", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "13", "APR_Descricao": "Medicamento Vencido", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "6", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "14", "APR_Descricao": "Avaria de Medicamentos", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "6", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "15", "APR_Descricao": "Diverg\u00c3\u00aancias de Volumes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "7", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "16", "APR_Descricao": "Avarias no Recebimento", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "7", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "17", "APR_Descricao": "Problemas Espec\u00c3\u00adficos", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "7", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "18", "APR_Descricao": "Pedidos de Compras", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "7", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "19", "APR_Descricao": "Diverg\u00c3\u00aancias de Volumes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "8", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "20", "APR_Descricao": "Avarias na Entrega ao Cliente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "8", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "21", "APR_Descricao": "Problema Espec\u00c3\u00adfico", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "8", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "22", "APR_Descricao": "Avarias de Produtos", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "23", "APR_Descricao": "Nota Fiscal Entrada", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "24", "APR_Descricao": "Nota Fiscal Sa\u00c3\u00adda", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "25", "APR_Descricao": "Pre\u00c3\u00a7o Divergente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "26", "APR_Descricao": "Carta de Corre\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "27", "APR_Descricao": "Cota\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "28", "APR_Descricao": "Prazo de Entrega de Mercadoria do Cliente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "29", "APR_Descricao": "Pedido para Lan\u00c3\u00a7ar", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "30", "APR_Descricao": "Pedido para Excluir", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "31", "APR_Descricao": "Pedido para Alterar Pre\u00c3\u00a7o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "32", "APR_Descricao": "Pedido para Alterar Produto", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "33", "APR_Descricao": "Pedido de Troca", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "34", "APR_Descricao": "Pedido com Pend\u00c3\u00aancia", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "35", "APR_Descricao": "Cadastro de Cliente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "36", "APR_Descricao": "Atualiza\u00c3\u00a7\u00c3\u00a3o de Cadastro", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "37", "APR_Descricao": "Envio de Solicita\u00c3\u00a7\u00c3\u00a3o de Viagem", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "38", "APR_Descricao": "Cobran\u00c3\u00a7a de Clientes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "39", "APR_Descricao": "Edital", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "40", "APR_Descricao": "Cronograma de Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "41", "APR_Descricao": "Proposta", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "42", "APR_Descricao": "Documenta\u00c3\u00a7\u00c3\u00a3o para Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "43", "APR_Descricao": "Documenta\u00c3\u00a7\u00c3\u00a3o Espec\u00c3\u00adfica (Cart\u00c3\u00b3rio)", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "44", "APR_Descricao": "Certid\u00c3\u00b5es", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "45", "APR_Descricao": "Registros e CBPF", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "46", "APR_Descricao": "Ata\/Contrato", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "47", "APR_Descricao": "Mapa", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "48", "APR_Descricao": "Cota\u00c3\u00a7\u00c3\u00a3o para Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "49", "APR_Descricao": "Cota\u00c3\u00a7\u00c3\u00a3o para Venda Direta", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "50", "APR_Descricao": "Servi\u00c3\u00a7o de Correio", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "51", "APR_Descricao": "Documentos para Arquivar", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "52", "APR_Descricao": "Pedido de Reequil\u00c3\u00adbrio Financeiro", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "53", "APR_Descricao": "Pedido sem Pre\u00c3\u00a7o (Custo)", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "54", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "55", "APR_Descricao": "Recurso", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "56", "APR_Descricao": "Ades\u00c3\u00a3o de Ata\/Contrato", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "57", "APR_Descricao": "Elabora\u00c3\u00a7\u00c3\u00a3o de Documento Espec\u00c3\u00adfico", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "58", "APR_Descricao": "Envio de Solicita\u00c3\u00a7\u00c3\u00a3o de Viagem", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "59", "APR_Descricao": "Outros", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "60", "APR_Descricao": "Cobran\u00c3\u00a7a de Clientes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "13", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "61", "APR_Descricao": "Pend\u00c3\u00aancia de Mercadorias", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "13", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "62", "APR_Descricao": "Outros", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "13", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "63", "APR_Descricao": "Avaria", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "64", "APR_Descricao": "Pedido Pendente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "65", "APR_Descricao": "Cobran\u00c3\u00a7a de Clientes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "66", "APR_Descricao": "Mercadoria Devolvida", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "67", "APR_Descricao": "Cadastro de Cliente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "68", "APR_Descricao": "Outros", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "69", "APR_Descricao": "Edital", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "70", "APR_Descricao": "Cronograma de Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "71", "APR_Descricao": "Proposta", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "72", "APR_Descricao": "Documenta\u00c3\u00a7\u00c3\u00a3o para Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "73", "APR_Descricao": "Documenta\u00c3\u00a7\u00c3\u00a3o Espec\u00c3\u00adfica (Cart\u00c3\u00b3rio)", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "74", "APR_Descricao": "Certid\u00c3\u00b5es", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "75", "APR_Descricao": "Registros e CBPF", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "76", "APR_Descricao": "Ata\/Contrato", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "77", "APR_Descricao": "Mapa", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "78", "APR_Descricao": "Cota\u00c3\u00a7\u00c3\u00a3o para Licita\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "79", "APR_Descricao": "Cota\u00c3\u00a7\u00c3\u00a3o para Venda Direta", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "80", "APR_Descricao": "Servi\u00c3\u00a7o de Correio", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "82", "APR_Descricao": "Documentos para Arquivar", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "83", "APR_Descricao": "Pedido de Reequil\u00c3\u00adbrio Financeiro", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "84", "APR_Descricao": "Envio de Solicita\u00c3\u00a7\u00c3\u00a3o de Viagem", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "85", "APR_Descricao": "Cadastro de Cliente", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "86", "APR_Descricao": "Atualiza\u00c3\u00a7\u00c3\u00a3o de Cadastro", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "87", "APR_Descricao": "Pedido para Lan\u00c3\u00a7ar", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "88", "APR_Descricao": "Pedido para Excluir", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "89", "APR_Descricao": "Pedido sem Pre\u00c3\u00a7o (Custo)", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "90", "APR_Descricao": "Pedido de Troca", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "91", "APR_Descricao": "Pedido com Pend\u00c3\u00aancia", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "92", "APR_Descricao": "Cobran\u00c3\u00a7a de Clientes", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "93", "APR_Descricao": "Outros", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "16", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "94", "APR_Descricao": "Teste", "APR_Prazo": "12", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "1" },
    { "APR_Id": "95", "APR_Descricao": "Cadastro de Fornecedor", "APR_Prazo": "48", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "96", "APR_Descricao": "Cadastro", "APR_Prazo": "2", "APR_TipoDados": "d", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "97", "APR_Descricao": "Cadastro", "APR_Prazo": "2", "APR_TipoDados": "d", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "11" },
    { "APR_Id": "98", "APR_Descricao": "ERRO NO SISTEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "99", "APR_Descricao": "ERRO NO LOGIN", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "100", "APR_Descricao": "ERRO EMAIL", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "101", "APR_Descricao": "COMPUTADOR NAO LIGA", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "102", "APR_Descricao": "INSTALAR IMPRESSORA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "103", "APR_Descricao": "COMPUTADOR SEM REDE", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "104", "APR_Descricao": "WIFI ", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "105", "APR_Descricao": "TECLADO OU MOUSE NAO FUNCIONA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "106", "APR_Descricao": "ERRO IMPRESSORA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "107", "APR_Descricao": "INSTALA\u00c3\u2021\u00c3\u201aO", "APR_Prazo": "2", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "108", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u0192O DE SITE", "APR_Prazo": "2", "APR_TipoDados": "h", "ARE_Id": "3", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "109", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u201aO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "110", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "111", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "8", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "112", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "7", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "113", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "114", "APR_Descricao": "MB", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "18", "APR_Status": "0", "USR_Id": "45" },
    { "APR_Id": "116", "APR_Descricao": "INSTALA\u00c3\u2021\u00c3\u201aO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "117", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u0192O DE SITE", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "118", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u201aO SISTEMA", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "119", "APR_Descricao": "PROBLEMA DE REDE", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "120", "APR_Descricao": "WIFI", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "121", "APR_Descricao": "TROCA DE PE\u00c3\u2021A E EQUIPAMENTO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "122", "APR_Descricao": "IMPRESSORA", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "123", "APR_Descricao": "EMAIL", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "124", "APR_Descricao": "ERRO SISTEMA", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "125", "APR_Descricao": "ATUALIZAR CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "19", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "126", "APR_Descricao": "ATUALIZAR PRE\u00c3\u2021O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "19", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "127", "APR_Descricao": "ALTERA\u00c3\u2021\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "128", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "19", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "129", "APR_Descricao": "PAGAMENTOS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "15", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "130", "APR_Descricao": "ALTERA\u00c3\u2021\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "15", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "131", "APR_Descricao": "RECIBO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "15", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "132", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "15", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "133", "APR_Descricao": "PROCESSO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "134", "APR_Descricao": "PRE\u00c3\u2021O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "135", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "14", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "136", "APR_Descricao": "COMPRAS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "137", "APR_Descricao": "PREG\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "138", "APR_Descricao": "INFORMATIVO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "139", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "20", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "140", "APR_Descricao": "NOTA FISCAL", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "141", "APR_Descricao": "LIBERA\u00c3\u2021\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "142", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "143", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "144", "APR_Descricao": "CONFERIR", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "145", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "146", "APR_Descricao": "ETIQUETAS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "147", "APR_Descricao": "DIVERGENCIA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "148", "APR_Descricao": "PRODUTO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "149", "APR_Descricao": "LOTE", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "21", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "150", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "6", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "151", "APR_Descricao": "COMPRAS", "APR_Prazo": "10", "APR_TipoDados": "d", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "152", "APR_Descricao": "OUTROS", "APR_Prazo": "2", "APR_TipoDados": "h", "ARE_Id": "22", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "153", "APR_Descricao": "CADASTRO", "APR_Prazo": "2", "APR_TipoDados": "h", "ARE_Id": "22", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "154", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "22", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "155", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "22", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "156", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "23", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "157", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "23", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "158", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "25", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "159", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "25", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "160", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "25", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "161", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "26", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "162", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "26", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "163", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "26", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "164", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "26", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "165", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "27", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "166", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "m", "ARE_Id": "27", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "167", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "27", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "168", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "27", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "169", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "28", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "170", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "28", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "171", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "28", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "172", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "28", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "173", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "29", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "174", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "29", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "175", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "29", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "176", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "29", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "177", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "30", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "178", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "30", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "179", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "30", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "180", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "181", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "182", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "183", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "184", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "185", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "32", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "186", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "32", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "187", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "32", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "188", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "32", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "189", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "33", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "190", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "33", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "191", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "33", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "192", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "33", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "193", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "34", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "194", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "34", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "195", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "34", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "196", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "34", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "197", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "35", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "198", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "35", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "199", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "35", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "200", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "35", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "201", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "36", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "202", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "36", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "203", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "36", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "204", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "36", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "205", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "37", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "206", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "37", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "207", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "37", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "208", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "38", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "209", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "38", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "210", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "38", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "211", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "38", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "212", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "39", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "213", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "39", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "214", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "40", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "215", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "40", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "216", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "40", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "217", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "40", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "218", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "41", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "219", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "41", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "220", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "41", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "221", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "41", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "222", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "42", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "223", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "43", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "224", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "43", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "225", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "43", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "226", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "43", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "227", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "44", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "228", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "44", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "229", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "44", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "230", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "44", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "231", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "45", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "232", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "45", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "233", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "45", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "234", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "45", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "235", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "46", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "236", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "46", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "237", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "46", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "238", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "46", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "239", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "47", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "240", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "47", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "241", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "47", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "242", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "47", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "243", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "23", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "244", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "23", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "245", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "24", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "246", "APR_Descricao": "COMUNICADO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "247", "APR_Descricao": "AVISO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "248", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "26", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "249", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "27", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "250", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "28", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "251", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "31", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "252", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "32", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "253", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "37", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "254", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "39", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "255", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "41", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "256", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "44", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "257", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "45", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "258", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "46", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "259", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "24", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "260", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "49", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "261", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "49", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "262", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "49", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "263", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "49", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "264", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "50", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "265", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "50", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "266", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "50", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "267", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "51", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "268", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "51", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "269", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "51", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "270", "APR_Descricao": "COMPRAS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "51", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "271", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "48", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "272", "APR_Descricao": "ALTERA\u00c3\u2021\u00c3\u0192O", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "48", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "273", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "48", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "274", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "52", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "275", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "52", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "276", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "53", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "277", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "53", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "278", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "53", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "279", "APR_Descricao": "COMUNICADO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "53", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "280", "APR_Descricao": "NOTIFICA\u00c3\u2021\u00c3\u201aO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "281", "APR_Descricao": "FINANCEIRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "54", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "282", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "54", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "283", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "54", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "284", "APR_Descricao": "COBRAN\u00c3\u2021A", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "54", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "285", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "54", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "286", "APR_Descricao": "CADASTRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "56", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "287", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "56", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "288", "APR_Descricao": "PROCESSO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "56", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "289", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "56", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "290", "APR_Descricao": "Comprovante de entrega", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "291", "APR_Descricao": "NOTA FISCAL", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "292", "APR_Descricao": "NOTA FISCAL", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "12", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "293", "APR_Descricao": "NOTA FISCAL DEVOLU\u00c3\u2021\u00c3\u2022ES", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "11", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "294", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00b5es", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "57", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "295", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00b5es", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "58", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "296", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "57", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "297", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "58", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "298", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "58", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "299", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "57", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "300", "APR_Descricao": "Notifica\u00c3\u00a7\u00c3\u00b5es", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "301", "APR_Descricao": "PROBLEMA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "302", "APR_Descricao": "PROCESSO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "303", "APR_Descricao": "PROCESSO", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "4", "APR_Status": "0", "USR_Id": "30" },
    { "APR_Id": "304", "APR_Descricao": "OUTROS", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "4", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "305", "APR_Descricao": "ASSINATURA", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "306", "APR_Descricao": "Teste 01", "APR_Prazo": "10", "APR_TipoDados": "d", "ARE_Id": "59", "APR_Status": "1", "USR_Id": "1" },
    { "APR_Id": "307", "APR_Descricao": "NOTA FISCAL ERRO", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "308", "APR_Descricao": "Cadastro de Clientes", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "60", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "309", "APR_Descricao": "Atualiza\u00c3\u00a7\u00c3\u00a3o de Cadastro", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "60", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "310", "APR_Descricao": "SENHA", "APR_Prazo": "50", "APR_TipoDados": "d", "ARE_Id": "18", "APR_Status": "1", "USR_Id": "30" },
    { "APR_Id": "311", "APR_Descricao": "Corre\u00c3\u00a7\u00c3\u00a3o de NF", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "312", "APR_Descricao": "Devolu\u00c3\u00a7\u00c3\u00a3o de NF (Coleta)", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "313", "APR_Descricao": "Carta de Corre\u00c3\u00a7\u00c3\u00a3o", "APR_Prazo": "1", "APR_TipoDados": "h", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "314", "APR_Descricao": "2\u00c2\u00aa via de Nota Fiscal", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "315", "APR_Descricao": "Emiss\u00c3\u00a3o de NF de Simples Remessa (Acompanhar mercadoria para outro Estado)", "APR_Prazo": "1", "APR_TipoDados": "d", "ARE_Id": "9", "APR_Status": "1", "USR_Id": "13" },
    { "APR_Id": "316", "APR_Descricao": "Carta de Indisponibilidade\/Previs\u00c3\u00a3o", "APR_Prazo": "5", "APR_TipoDados": "d", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "64" },
    { "APR_Id": "317", "APR_Descricao": "Nota Fiscal", "APR_Prazo": "2", "APR_TipoDados": "d", "ARE_Id": "10", "APR_Status": "1", "USR_Id": "64" }
]

export default problems;